### ISSUE TITLE
Dynamic autocomplete

### ISSUE THREAD

**Issue by Leka74** [trixnz/vscode-lua#1]
Is there any plan to implement dynamic autocompletion (for custom functions, tables, variables)?

**Comment by trixnz** [comment]
I've just pushed 0.5.0 to the marketplace which adds early support for table intellisense, but I'm not sure what you mean with custom functions and variables? These should already show up as suggestions.

If 0.5.0 doesn't solve your needs, please provide some examples and I'll work on a fix :).

**Comment by Leka74** [comment]
I just updated to 0.5.0 and it's working as I intended, so thank you.

Since we're on this topic already, can we expect support for function parameters & require'd modules as well with intellisense?

Also is there any plan to add something like docstrings in Python for this extension? That'd be very useful.

Thank you and nice work.

**Comment by macjabeth** [comment]
Wasn't sure whether to create a new issue for this, so I hope you don't mind me adding it here!

I was wondering if you could also add autocomplete support for the **self** parameter in tables?

```lua
module = {
  enabled = false,
  toggle = function(self)
    -- self should have autocomplete here
    self.enabled = not self.enabled
    print("Module " .. (self.enabled and "Enabled" or "Disabled") .. "!")
  end,
}
```

**Comment by trixnz** [comment]
@Leka74 sure, can you make separate issues with a blurb about what each one entails?

@macjabeth in my test, `self` autocompleted just fine. Do you mean it should derive the type of `self` to be `module` and add `enabled` and `toggled` as suggestions on `self.`? Should be possible without too much investment. Can you also make a separate issue?

"Dynamic autocomplete" seems a bit broad for these various tasks, but a great discussion board going forward 😄

**Comment by macjabeth** [comment]
@trixnz Heyo, I did mean `self` being recognised as a module and providing autocompletion for items inside (ie. `self.` should then show `enabled` as an option).

I'll make a separate issue for it.

Thanks!

**Comment by ChristopherLClark** [comment]
If i created my own modules, how do I add them to the autocomplete? or More clearly how do i tell my current project about the module in the same folder tree.
