### ISSUE TITLE
Can not analyze symbols with Chinese

### ISSUE THREAD

**Issue by bbxiong1999** [trixnz/vscode-lua#12]
Can not analyze the Chinese function name, variable name, please add the analysis of Chinese function name and variable name support.
Luajit can support gbk or utf8 Chinese function name and variable name.

example
`
function 中文函数名(参数1,参数2)
    local 中文变量 = "Chinese variable name"
end

`

**Comment by trixnz** [comment]
According to the Lua 5.2 [manual](https://www.lua.org/manual/5.2/manual.html#8.1), Lua identifiers cannot use locale-dependent letters. As a result, the library we use to parse Lua, [luaparse](https://github.com/oxyc/luaparse), does not support utf-8 encoded identifiers.

Unfortunately there's nothing I can do about that.
