### ISSUE TITLE
Check Luacheck

### ISSUE THREAD

**Issue by SWSAmor** [trixnz/vscode-lua#13]
Luaparse is working good. But how could i know is luacheck working?

**Comment by trixnz** [comment]
Assuming you followed the instructions in https://github.com/trixnz/vscode-lua#luacheck, it should start populating your diagnostics window and source code with hints.

**Comment by SWSAmor** [comment]
I didn't see any hints in the diagnostic window. Luacheck is working from cmd. Maybe the path syntax is wrong. Here is my luacheckPath. Would you check it? I'm on windows.
"lua.luacheckPath": "d:\\Programok\\luacheck",

**Comment by trixnz** [comment]
`lua.luaCheckPath` must point to the executable file, not just the folder it resides in.
