### ISSUE TITLE
Using Tarantool or other third party libraries

### ISSUE THREAD

**Issue by SWSAmor** [trixnz/vscode-lua#14]
Is there any option to use a library and the library functions to be known by the luacheck? For example i use tarantool and i get 
```
severity: 'Warning' message: 'accessing undefined variable 'box'' at: '44,5' source: 'luacheck'
```
but the box is a builtin function.

Same question for autocompletion. Would be nice if autocompletion box could contain the functions of the third party libraries. Of course the developers need to make a description file for these, but this isn't a problem i think. I glad to make the Tarantools one. ;-)

**Comment by trixnz** [comment]
To answer the first question, that is configured by creating a `.luacheckrc` in your project directory and adding the necessary items. You can read more about the luacheck config here: https://luacheck.readthedocs.io/en/stable/config.html. I'm not sure what Tarantool is, or if someone has already created a luacheck config for it, but you could also disable the verbose warnings if they're bothering you.

As for autocompletion, that would be nice and would tie in to parsing of `require()`'d modules. I haven't got around to doing that, so for now this is not supported :disappointed: .
