### ISSUE TITLE
Code formatting setup

### ISSUE THREAD

**Issue by StoneFalcon** [trixnz/vscode-lua#16]
I think will be good to add formatting parameters to VSCode config. For example at big monitors it wrap code at half of string length and i don't find any way to correct this behaviour.

After formatting code may look like:

```lua
 if
        last_sync_version ~= nil and cur_version ~= nil and (not is_str_empty(cur_map_id)) and cur_level ~= nil and
            save_data ~= nil
     then
          some code here....
end
```

It will be great to put code wrapping length somewhere to save lines and compact code after formatting.

**Comment by trixnz** [comment]
This is checked in and should be available as 0.8.0. You can refer to https://github.com/trixnz/vscode-lua#settings for the formatting settings. :smile:
