### ISSUE TITLE
Auto-indent feature request

### ISSUE THREAD

**Issue by eniallator** [trixnz/vscode-lua#19]
when making a new line after an if/for/while/function etc. the new line should be indented by 1 tab (however many spaces is in the user's settings)

**Comment by jonathan-aes** [comment]
This may be possible using the languages-configuration file... I'm gonna try to work something out.

https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages

**Comment by Nexela** [comment]
lua-indent extension does this, But I agree it would be better to have it/something like it in this extension

**Comment by trixnz** [comment]
Looks like some folks have already begun fixing this in the official vscode repo: https://github.com/Microsoft/vscode/pull/31696 and https://github.com/Microsoft/vscode/pull/34303. I'd much prefer that solution, but will keep an eye out to see if it makes it in. If not, i'd be happy to implement it in the extension.

**Comment by eniallator** [comment]
Ah cool, thanks for the info. I've switched from atom to vs code (mainly because of how resource intensive atom was) and i got used to the lua package i used. If the official vs code repo will include this in the future, don't worry about it - it's just a small detail. however if it's an easy implementation on your end then it might be cool to see :)

**Comment by eniallator** [comment]
Another detail that would be nice as part of the auto-indentation is if you type in 'end', it will automatically go back 1 tab. More to this feature would be if you delete the end, as soon as it doesn't spell 'end', it reset back to whatever tabbing there was initially. Also if you could, it would be cool to detect what the end was closing and go to that tab size and say if it were on the same line as the thing it was closing, it wouldn't do anything e.g: `if foo then bar() end`.

**Comment by trixnz** [comment]
Looks like this was merged into vscode 2 hours ago. Can you check with the next insider's build to see if it meets what you want?

**Comment by trixnz** [comment]
@eniallator Can you please confirm if this is resolved by the latest vscode update? From my cursory glance, it appears to be.

**Comment by Nexela** [comment]
Seems to indent just fine for me!
