### ISSUE TITLE
Not reading files[] in luacheckrc

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#20]
![desktop screenshot 2017 09 18 - 17 37 44 24](https://user-images.githubusercontent.com/13972192/30571647-37174462-9cb7-11e7-8b91-d0fd25f5a28d.png)

**Comment by Nexela** [comment]
```js
const process = child_process_1.spawn(settings.luacheckPath, ['-', '--no-color', '--ranges', '--codes'], {
            cwd: dir
        });
`
If I had to guess - stdin doesn't send the file path

**Comment by Nexela** [comment]
```js
'--filename='+uri
```
Adding --filename is what is needed, Not sure if that is the best way I will leave the implementation up to you.  Thanks for looking into this.

**Comment by trixnz** [comment]
Nice find!
