### ISSUE TITLE
comparing with git log leaves problem windows open pointing to temp files

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#22]
Files in %localappdata%/temp should not be linted, or at the very least should close when the tmp file is closed
![image](https://user-images.githubusercontent.com/13972192/30574037-664b72c2-9cc5-11e7-82a0-1d531bb1cbf7.png)

**Comment by trixnz** [comment]
I've disabled linting on the `showModifications` schema, but I suspect there may be more edge cases. Should be fixed for now, though. Thanks!
