### ISSUE TITLE
Minor - Refocusing/saving with no changes editor should relint

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#23]
Not sure if possible,   but refocusing an editor should re-lint the active editor file. For those of us editing .luacheckrc files

Right now to force a re-lint I have to make a change to the file and re-save it  (the re-save might not be necessary but the edit it) 

In Atom I could easily do something like this by quickly saving the file with ctrl-s.

**Comment by trixnz** [comment]
From what I can see, the editor doesn't give any events for when a file was attempted to be saved when no changes were present. I assume it just early fails. 

I like the idea though. Would re-linting all open documents when a file named `.luacheckrc` is saved from within vscode work as an alternative?

**Comment by Nexela** [comment]
If there is no editor focus event or attempt-save event then I wouldn't worry about it too much. Having it run on all open documents could be a problem if some of the lua files are big and the luacheckrc is massive :)
