### ISSUE TITLE
Support region folding feature

### ISSUE THREAD

**Issue by eddylin** [trixnz/vscode-lua#25]
Hi, can you add support for new region folding feature?

**Comment by trixnz** [comment]
This would be possible, although I don't believe there is a standard for Lua regions? I would be hesitant to add an arbitrary region type as it may not suit everybody's needs. 

What would you suggest?

**Comment by eddylin** [comment]
Maybe we can define these two
-- region
-- endregion
-- #region
-- #endregion
like these predefined two in vscode
//#region
//#endregion
//region
//endregion
in TypeScript/JavaScript?
They are both single line comments, will work fine in editors that don't support region maker.

**Comment by Janfel** [comment]
The region markers suggested above seem to be the quasi standard for VSCode and are currently implemented by:

* JavaScript/TypeScript
* CSS/Less/SCSS
* Coffeescript
* F#
* Java
* HTML
* PHP
* Powershell
* Python
* CMD/BAT
* Markdown
* Rust

As this isn’t just a JS/TS thing anymore, I would encourage you to implement this feature, if just for feature consistency with the rest of the editor.

**Comment by henridev** [comment]
Hi there is a great vscode extension called '#region folding for vscode' 

I installed it to work with lua by including a config inside of my vscode settings. 
It looks like the following:

![image](https://user-images.githubusercontent.com/63241061/83136808-64125000-a0e8-11ea-9afb-3fb3387def09.png)

Then inside of my files i can fold the regions.
Like so:

![image](https://user-images.githubusercontent.com/63241061/83136911-899f5980-a0e8-11ea-85c2-a2c0fc5084dc.png)
