### ISSUE TITLE
keep shebang when formatting?

### ISSUE THREAD

**Issue by weshardee** [trixnz/vscode-lua#26]
Is there a way to configure the formatter not to remove `#!/usr/bin/env lua` at the beginning of a file?

**Comment by trixnz** [comment]
Sorry about that. Just fixed this in https://github.com/trixnz/lua-fmt/commit/9312765fc41118efc1520b26d4572c298696849a. Will be pushing a new build of `vscode-lua` shortly.

**Comment by trixnz** [comment]
0.9.0 should be live now, works fine on my end :smile:

**Comment by weshardee** [comment]
thanks!
