### ISSUE TITLE
Problems window not clearing up when closing file

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#32]
Opened a folder, opened a file (FILE) that was not in the folder, closed FILE, warnings stayed in the problems window.  

Expected, problems to disappear 

Also I think this one was reported before but same kind of issue
Open a file, Compare with previous version (or some kind of split compare that opens a temp file, split window/temp file. warnings stay

Expected Don't lint temporary files, and problems to disappear when closing.

Keep up the awesome work!

**Comment by trixnz** [comment]
I couldn't reproduce the second issue; files in the modification view are excluded from the linting service. If you can repro it with more detailed instructions, feel free to open another ticket. Thanks! 😄
