### ISSUE TITLE
Request Formatter and table as parameter

### ISSUE THREAD

**Issue by Nexela** [trixnz/vscode-lua#33]
Can there be an option to not add a space between a word/function and a {

currently this `myfunc{a}` formats to `myfunc {a}`

**Comment by trixnz** [comment]
This kind of behaviour is somewhat tricky to accommodate on such a fine granularity, but feel free to make an issue on https://github.com/trixnz/lua-fmt for the functionality. This repo is just for the editor side of things, so I'll keep this open until we settle on a `lua-fmt` solution.

**Comment by Nexela** [comment]
I would say not to worry about it then. It is a minor detail and it really
doesn't bother me all that much anyway. :p

**Comment by Nexela** [comment]
Closing this issue
