### ISSUE TITLE
Respect file indent settings

### ISSUE THREAD

**Issue by mspielberg** [trixnz/vscode-lua#37]
It looks like lua-fmt accepts `--indent-count` and `--use-tabs`, but vscode-lua does not propagate the current buffer's indent settings to these options. Would this be something easy to hook up?

**Comment by trixnz** [comment]
This should be fixed by https://github.com/trixnz/vscode-lua/commit/e41418d957f3605e7d6d0dd097b1f3e42ca27d71 and will be available in `0.10.0` momentarily.😃
