### ISSUE TITLE
Error: write EOF

### ISSUE THREAD

**Issue by Stanzilla** [trixnz/vscode-lua#42]
Getting 
```
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)
[Info  - 18:34:27] Connection to server got closed. Server will restart.
[Error - 18:34:36] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'symbols' of undefined
  Code: -32603 
[Error - 18:34:37] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'symbols' of undefined
  Code: -32603 
```

when playing around with super long files. https://github.com/WeakAuras/WeakAuras2/blob/master/.luacheckrc

**Comment by trixnz** [comment]
I can't seem to replicate this, what version of the extension are you using? And what steps are required to trigger the error?

I opened the file and created a syntax error and it seemed to handle it correctly.

**Comment by Stanzilla** [comment]
Weird, I'm on 0.10.1. It's even enough if I open it here.

**Comment by trixnz** [comment]
![image](https://user-images.githubusercontent.com/2995953/36391204-d48e7e1a-15a5-11e8-8ed5-7d67326b34e5.png)

![image](https://user-images.githubusercontent.com/2995953/36391221-e917e0ec-15a5-11e8-91c7-94d0fb2d3a19.png)

It seems to be functioning nominally here for both files. Can you share your settings pertinent to the `lua` section?

**Comment by Stanzilla** [comment]
```
 "lua.luacheckPath": "luacheck.bat",
 "lua.preferLuaCheckErrors": true,
```

are the only global ones and this workspace has

```
{
  "lua.format.indentCount": 2,
  "luaformatter.spaces": 2
}
```

**Comment by trixnz** [comment]
I wonder if this is somehow related to #41, does the luacheck functionality work without the big file?

**Comment by Stanzilla** [comment]
Yeah it does and it even works with the big file, it just crashes sometimes. Can you try having .luacheckrc open and delete the last } in it and hit save. That just made it error here.

**Comment by trixnz** [comment]
Should be fixed by the latest update 😃. Nice find!

**Comment by Stanzilla** [comment]
Nice! Will try!

**Comment by Stanzilla** [comment]
Perfect, thanks!
