### ISSUE TITLE
Luacheck tries to lint itself

### ISSUE THREAD

**Issue by Stanzilla** [trixnz/vscode-lua#43]
I already saw in your screenshot in https://github.com/trixnz/vscode-lua/issues/42 that you have the same "problem" but currently luacheck tries to lint it's own .luacheckrc. Is that intended?

**Comment by Stanzilla** [comment]
I don't think that's correct though?

**Comment by nebularg** [comment]
luacheck itself only checks .lua files if you give it a path, pretty silly to change the behavior by default.

**Comment by trixnz** [comment]
I'm inclined to agree that it shouldn't lint itself. While your solution is quite clever @Nexela, I don't think we should force that expectation on everyone.

**Comment by Nexela** [comment]
We don't have to with the latest version of luacheck. It accounts for luacheckrc globals now.

**Comment by Nexela** [comment]
Also being able to lint the .luacheckrc file really helps when you have big luacheckrc files like I do.
