### ISSUE TITLE
Formatting a file with invalid syntax causes the "Output" window to pop up due to an error.

### ISSUE THREAD

**Issue by AmandaCameron** [trixnz/vscode-lua#45]
As a compulsive saver, this is somewhat annoying when I'm working on a file and hit save mid-stride. I'm fine with VSCode showing me an error, but the pop up of the output window because the textFormatter has errored is a bit annoying, and really breaks the flow of code.

This is mostly a problem because I have VS Code set to format on save (for formatting consistency) and I'm guessing it was assumed that formatting will always be a concious decision, instead of something that gets done automatically by the editor.

**Comment by trixnz** [comment]
I can appreciate that! I've just pushed a fix in `v0.12.4`, hopefully it should be less annoying now 😃
