### ISSUE TITLE
Document symbols feature request

### ISSUE THREAD

**Issue by Yanpas** [trixnz/vscode-lua#46]
Support method: ‘textDocument/documentSymbol’
Example:
![image](https://user-images.githubusercontent.com/7345761/39084880-4226bc9a-4584-11e8-8735-9f8acd8a9cc0.png)

**Comment by trixnz** [comment]
This is implemented already, see https://github.com/trixnz/vscode-lua/blob/master/server/src/services/documentSymbolService.ts.

**Comment by Yanpas** [comment]
Oh, see it
