### ISSUE TITLE
luacheck options via VS code

### ISSUE THREAD

**Issue by daw00kie** [trixnz/vscode-lua#50]
Is there any way to add options to the luacheck call when using it via VS code?  
I would like to add some globals I use that are in a require all my processes call

**Comment by Nexela** [comment]
While I can't directly answer your question I can provide this

Opinion alert: The best way to do this is with an .luacheckrc file in your
project

**Comment by daw00kie** [comment]
Thanks I missed you could define a config file.  It might be nice if you could define where that file is so you can have one common one.  At the moment I have it in the windows default but would like it in my project.

**Comment by Nexela** [comment]
I think it looks first in the directory of the file. Then in all
directories above until root.  Then in os specific user folder then finally
in application folder?  I believe it is explained in the docs


For example my luacheckrc for a group of mods for one game is in
/devel/game/.luacheckrc. and the mods will be in subgroups of that folder

Then I have a master luacheckrc in my user folder to define all my non
specific defaults
