### ISSUE TITLE
Coexistence with Lua snippets for Wikimedia

### ISSUE THREAD

**Issue by jeblad** [trixnz/vscode-lua#52]
Not sure why, but [Lua snippets for Wikimedia](https://marketplace.visualstudio.com/items?itemName=jeblad-3.WMFsnippets) does not work as expected when this extension is enabled. Somehow it fails as soon as the first terminator (like full stop) is added.

At least [Lua Intellisense](https://marketplace.visualstudio.com/items?itemName=mettra.lua-intellisense) has the same problem.

It seems like this affects intellisense too.

**Comment by FireSiku** [comment]
If it happens with multiple extensions, it's likely the problem comes from the Wikimedia extension not playing nicely with Intellisense in general and they might want to be aware of this [over here](https://github.com/jeblad/vscode-wikimediafunctions-snippets/issues)

**Comment by trixnz** [comment]
This seems to be fixed as of the time of writing, please re-open this issue if this is still a problem.

For reference, my VSCode version:
```
Version: 1.31.0-insider (user setup)
Commit: e02e44464c02d617b98d0a3265bf5efef7794436
Date: 2018-12-21T06:20:35.852Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
