### ISSUE TITLE
.luacheckrc in sibling directory to the checked scripts directory?

### ISSUE THREAD

**Issue by cadiremar** [trixnz/vscode-lua#58]
Is it possible to have the .luacheckrc config file in a sibling directory to the main scripts directory?
As in a structure like this:
root/
├── luacheck/
│   ├── .luacheckrc
├── scripts/
│   ├── several/
│   │   └── sub/
│   └── directories/

I understand luacheck tries to find a .luacheckrc file starting from the checked file and working upwards to the root catalog, but I haven't been able to figure out a way to keep it in a sub directory parralel to the directory a checked file is in.

This seems to work when running from the command line as in 
`path/to/luacheck.exe "../scripts/" --config luacheck/.luacheckrc`, but not when run via the vscode-lua extension

**Comment by jalovatt** [comment]
I'm having a similar issue, so I might as well chime in here rather than opening a new one.

In my case, I've got my config in `~/.config/luacheck/.luacheckrc`, which the Luacheck docs specify as a global default. Running Luacheck from the command line sees it, but for whatever reason it doesn't work when linting through _vscode-lua_.

**Comment by nzt4567** [comment]
Also keeping the config in the global default and it also gets ignored by _vscode-lua_

**Comment by trixnz** [comment]
I've added an option to specify a [custom `.luacheckrc` config](https://github.com/trixnz/vscode-lua/commit/ec08e47637836a835f3df6ffc14f144743bd1749) for situations like these, but could not reproduce the default search path not working. It seems to work fine here on Windows. Are you sure your VSCode is running under the same user as to where you've placed your config? 

If this is still an issue, please feel free to open a more specific issue and I'll take a look for you.

**Comment by jalovatt** [comment]
Any chance of a release? I tried building a local copy of the extension but I'm doing something wrong.
