### ISSUE TITLE
visual studio 2017 style code folding?

### ISSUE THREAD

**Issue by Shadowblitz16** [trixnz/vscode-lua#59]
can you add visual studio style code folding?

so lets say I have a foldable code region like this..
```
    if a == b then
       --stuff
    end
```

instead of it looking like this
```
    if a == b then 
    end
```

it looks more like this..
```
    if a == b then ...
```

this would work with `while`, `for` and `tables` too

**Comment by trixnz** [comment]
As far as I'm aware, this is entirely controlled by vscode, and extensions can't override the behaviour. I would check if an issue exists on the vscode repo, or otherwise think about opening one.
