### ISSUE TITLE
Hexadecimal number not correctly highlight in function arguments

### ISSUE THREAD

**Issue by Tankypon** [trixnz/vscode-lua#6]
Just a little bug during passing an hexadecimal number to a function argument
![image](https://cloud.githubusercontent.com/assets/8155675/25949802/155d4458-3659-11e7-9213-e2d66bd794d4.png)
The hexadecimal number is not correctly highlight.

**Comment by trixnz** [comment]
Looks like this was resolved 3 days ago: https://github.com/Microsoft/vscode/commit/145310aea5e41c6af8de4aaf7910bdb90f0e4fea. The Lua grammars are built into vscode, so you'll need to either use an insider's build or wait for the next release.

**Comment by Tankypon** [comment]
Ok, thank you. I'll wait the next release.
