### ISSUE TITLE
Support bitwise syntax

### ISSUE THREAD

**Issue by italomaia** [trixnz/vscode-lua#7]
Just got myself a syntax error for:

`v = v >> 1`

Seems fine, to me.

**Comment by trixnz** [comment]
This is a result of the extension making an assumption about the version of Lua being used; `luaparse` supports Lua 5.3, but the extension doesn't facilitate a means to change it from 5.1. I'm not entirely sure how I want to support this, but I suspect there might be a UI feature in the editor I can plug in to.

**Comment by italomaia** [comment]
https://github.com/oxyc/luaparse/issues/50#event-1117714120 <=

**Comment by trixnz** [comment]
Fixed in v0.7.0 by https://github.com/trixnz/vscode-lua/commit/36aba94ac7f0dbbbccc3674629404e190974e9ec
