### ISSUE TITLE
SOLVED: Intellisense no longer working

### ISSUE THREAD

**Issue by giaffodesigns** [trixnz/vscode-lua#79]
FIXED: Issue was not caused by vscode-lua, but by Python extensions. I don't have any explanations, but disabling the python extensions restored everything back to normal, and I was able to recreate the issue on another maching by installing the same extensions.

---------------- ORIGINAL POST ----------------
Just updated to VScode v1.40.0

Intellisense no longer appears to be working for Lua. Python and JS are having no issues. 
The vscode-lua plugin was uninstalled and reinstalled, settings were checked that suggestions are enabled, both through the settings menu and in the settings.json file, specifically setting all fields to true in "editor.quickSuggestions", includeing "other", "comments", and "strings".

**Comment by giaffodesigns** [comment]
Issue still present but I tried reinstalling an older version and still no luck so my assumed cause appears to be wrong.

**Comment by RiQuY** [comment]
I can confirm that Intellisense is not working too, but errorchecker works fine.

**Comment by giaffodesigns** [comment]
For me, the issue turned out to be extensions I had installed for Python that were causing the issue. I disabled those extensions and everything went back to normal.
