### ISSUE TITLE
Support for formatting

### ISSUE THREAD

**Issue by Enzojz** [trixnz/vscode-lua#9]
Hello,

Is it possible to add support to make automatic formatting? Thanks !

best regards,
Zheng

**Comment by trixnz** [comment]
Hi,
Could you please explain a little more what you mean?

**Comment by Enzojz** [comment]
Something like formatting with a pretty printer etc...

**Comment by trixnz** [comment]
Oh, this functionality is already implemented. You can access it via the built in vscode keybinds (Shift + Alt + F on Windows)

**Comment by Enzojz** [comment]
Hello,

Just have tried it it seems having two problems:

1. After this function, the editor goes to the end of the file, which is annoying.
2. It puts all nested tables inline, it should be happen.

Could you improve it?

**Comment by trixnz** [comment]
Hi,

1) I suspect you may be selecting all of the text before running it, as I just tested it and it worked fine. Can you try again without selecting any text?
2) Please take this to the [luafmt](https://github.com/trixnz/lua-fmt/issues) issue tracker and create a bug report with a reproduction case and your expected output.

Cheers

**Comment by Enzojz** [comment]
Hi,

1. I think anyway "jump to the end" when without selecting all is disturbing, since I will lost my input cursor, same as to doing selection all before it, and if I want to format all, why I need to select all?
2. I will create a ticket there.

**Comment by trixnz** [comment]
You *don't* need to select all. Here's a video demonstrating how it should work:


![2017-07-17_21-31-19](https://user-images.githubusercontent.com/2995953/28286164-96dc219e-6b37-11e7-91b5-a7134805aaa7.gif)

**Comment by Enzojz** [comment]
Ok, I have firgure out what it is:

Because of the first problem, my lua file gets much less lines after formatting, however, the cursor stays always on the same position. 

I think it's a bug, since in your video it's not the case. 
I am on windows 10.

**Comment by Enzojz** [comment]
I tested again, it seems context related, I work on a simple code like yours it work correctly, but not on my own real project:

for example this one:

https://github.com/Enzojz/flying_junction_1/blob/master/res/scripts/junction_assoc.lua

**Comment by trixnz** [comment]
I looked into it a bit, and its more than likely because `luafmt` returns the whole formatted file as a single edit. I'll look into adding diff support to `luafmt` so we can provide minimal edits to vscode.

**Comment by Enzojz** [comment]
Not sure, since I have tested again on this file, which isn't with any unicode letter, it worked fine.

https://github.com/Enzojz/flying_junction_1/blob/master/res/scripts/junction.lua

Just for information.

**Comment by trixnz** [comment]
Thanks for the use-cases; I'll use them when implementing diff support. You can follow https://github.com/trixnz/vscode-lua/issues/10 and https://github.com/trixnz/lua-fmt/issues/13 to keep track of progress.

Apologies for the bugs!

**Comment by Enzojz** [comment]
Ok. Thank you.

**Comment by trixnz** [comment]
The new version on the marketplace (0.6.2) should fix this for you. Be advised though, the first format you run may not preserve the cursor position if the file has not been formatted before, as the number of edits will be fairly large and vscode loses track.

After that though, the cursor should stay with you through formats so long as the file is reasonably close to the same layout that `luafmt` will be outputting.

**Comment by Enzojz** [comment]
Thank you. 

Could you have a look into line breaking issue.

I think inline functions should stay inline after formatting:

like in my code:

'''
    return {
        normal = pipe.new
        * func.map2(tracks1, tracks2,
            function(t1, t2)
                local seg = {junction.generateArc(t1)[1], junction.generateArc(t2)[2]}
                seg[1][2], seg[2][1] = average(seg[1][2], seg[2][1])
                seg[1][4], seg[2][3] = average(seg[1][4], seg[2][3])
                return pipe.new
                    * seg
                    * pipe.map(pipe.map(coor.vec2Tuple))
                    * pipe.zip({{false, false}, {false, false}}, {"edge", "snap"})
            end)
        * pipe.flatten()
        * station.prepareEdges
        * function(r) return func.with(r, {edges = coor.applyEdges(trans.mpt, trans.mvec)(r.edges)}) end,
        ext = pipe.new
        * func.map2(tracks1, tracks2,
            function(t1, t2)
                local seg = {junction.generateArc(t1)[3], junction.generateArc(t2)[4]}
                return pipe.new
                    * seg
                    * pipe.map(pipe.map(coor.vec2Tuple))
                    * pipe.zip({{true, false}, {false, true}}, {"edge", "snap"})
            end)
        * pipe.flatten()
        * station.prepareEdges
        * function(r) return func.with(r, {edges = coor.applyEdges(trans.mpt, trans.mvec)(r.edges)}) end
    }
'''

after formatting, it's not good as before, since inline functions are broken, and my pipe operators goes to the end of the line

I think the user should be able to configure on some formatting options. 

'''
    return {
        normal = pipe.new *
            func.map2(
                tracks1,
                tracks2,
                function(t1, t2)
                    local seg = {junction.generateArc(t1)[1], junction.generateArc(t2)[2]}
                    seg[1][2], seg[2][1] = average(seg[1][2], seg[2][1])
                    seg[1][4], seg[2][3] = average(seg[1][4], seg[2][3])
                    return pipe.new * seg * pipe.map(pipe.map(coor.vec2Tuple)) *
                        pipe.zip({{false, false}, {false, false}}, {"edge", "snap"})
                end
            ) *
            pipe.flatten() *
            station.prepareEdges *
            function(r)
                return func.with(r, {edges = coor.applyEdges(trans.mpt, trans.mvec)(r.edges)})
            end,
        ext = pipe.new *
            func.map2(
                tracks1,
                tracks2,
                function(t1, t2)
                    local seg = {junction.generateArc(t1)[3], junction.generateArc(t2)[4]}
                    return pipe.new * seg * pipe.map(pipe.map(coor.vec2Tuple)) *
                        pipe.zip({{true, false}, {false, true}}, {"edge", "snap"})
                end
            ) *
            pipe.flatten() *
            station.prepareEdges *
            function(r)
                return func.with(r, {edges = coor.applyEdges(trans.mpt, trans.mvec)(r.edges)})
            end
    }

'''
